name: benchmarks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - gha**

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dedicated-server
            compiler: g++-11
            architecture: -m64
            sourcefile: string.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: [self-hosted, linux, x64]
            install: g++-11
            command: sudo cset shield --exec -- nice -n -20 sudo -u gha ./benchmark
          # - name: dedicated-server
          #   compiler: g++-11
          #   architecture: -m64
          #   sourcefile: string_view.cpp
          #   compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
          #   outputfile: benchmark
          #   os: [self-hosted, linux, x64]
          #   install: g++-11
          #   command: sudo cset shield --exec -- nice -n -20 sudo -u gha ./benchmark
          # - name: dedicated-server
          #   compiler: g++-11
          #   architecture: -m64
          #   sourcefile: uint32.cpp
          #   compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
          #   outputfile: benchmark
          #   os: [self-hosted, linux, x64]
          #   install: g++-11
          #   command: sudo cset shield --exec -- nice -n -20 sudo -u gha ./benchmark
          # - name: dedicated-server
          #   compiler: g++-11
          #   architecture: -m64
          #   sourcefile: uint64.cpp
          #   compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
          #   outputfile: benchmark
          #   os: [self-hosted, linux, x64]
          #   install: g++-11
          #   command: sudo cset shield --exec -- nice -n -20 sudo -u gha ./benchmark
          - compiler: g++-11
            architecture: -m64
            sourcefile: string.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11
          - compiler: g++-11
            architecture: -m64
            sourcefile: string_view.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11
          - compiler: g++-11
            architecture: -m64
            sourcefile: uint32.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11
          - compiler: g++-11
            architecture: -m64
            sourcefile: uint64.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11
          - compiler: clang++-12
            architecture: -m64
            sourcefile: string.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
          - compiler: clang++-12
            architecture: -m64
            sourcefile: string_view.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
          - compiler: clang++-12
            architecture: -m64
            sourcefile: uint32.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
          - compiler: clang++-12
            architecture: -m64
            sourcefile: uint64.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
          - compiler: clang++-12
            architecture: -m64
            sourcefile: string.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev
          - compiler: clang++-12
            architecture: -m64
            sourcefile: string_view.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev
          - compiler: clang++-12
            architecture: -m64
            sourcefile: uint32.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev
          - compiler: clang++-12
            architecture: -m64
            sourcefile: uint64.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev
          - compiler: g++-11
            architecture: -m32
            sourcefile: string.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11 gcc-11-multilib g++-11-multilib
          - compiler: g++-11
            architecture: -m32
            sourcefile: string_view.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11 gcc-11-multilib g++-11-multilib
          - compiler: g++-11
            architecture: -m32
            sourcefile: uint32.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11 gcc-11-multilib g++-11-multilib
          - compiler: g++-11
            architecture: -m32
            sourcefile: uint64.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11 gcc-11-multilib g++-11-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: string.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: gcc-multilib g++-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: string_view.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: gcc-multilib g++-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: uint32.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: gcc-multilib g++-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: uint64.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: gcc-multilib g++-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: string.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev gcc-multilib g++-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: string_view.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev gcc-multilib g++-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: uint32.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev gcc-multilib g++-multilib
          - compiler: clang++-12
            architecture: -m32
            sourcefile: uint64.cpp
            compileroptions: -std=c++2a -O3 -stdlib=libc++ -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            os: ubuntu-20.04
            install: libc++-12-dev libc++abi-12-dev gcc-multilib g++-multilib

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        if: matrix.install
        run: |
          set -xe
          # sudo -E apt-add-repository -y ppa:ubuntu-toolchain-r/test
          echo "dpkg add-arch : "
          if uname -p | grep -q 'x86_64'; then sudo dpkg --add-architecture i386 ; fi
          sudo apt-get update -y
          echo "First set of packages: "
          sudo apt-get install -y ${{matrix.install}}
          
      - name: Install Boost
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/boostorg/boost.git boost-root
          cd boost-root
          git checkout boost-1.78.0
          git submodule update --init
          ./bootstrap.sh
          ./b2 -d0 headers
          
      - name: Install Abseil
        run: |
          cd $GITHUB_WORKSPACE
          git clone -b lts_2021_11_02 https://github.com/abseil/abseil-cpp.git abseil-root
      - name: Install fastrange
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/lemire/fastrange.git fastrange-root
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE
          ${{matrix.compiler}} --version
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.architecture}} ${{matrix.compileroptions}} -o ${{matrix.outputfile}} -I$GITHUB_WORKSPACE/boost-root -I$GITHUB_WORKSPACE/abseil-root -I$GITHUB_WORKSPACE/fastrange-root
      - name: Run benchmarks
        run: |
          ./${{matrix.outputfile}}
  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: cl
            architecture: x64
            sourcefile: string.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019
          - compiler: cl
            architecture: x64
            sourcefile: string_view.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019
          - compiler: cl
            architecture: x64
            sourcefile: uint32.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019
          - compiler: cl
            architecture: x64
            sourcefile: uint64.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019
          - compiler: cl
            architecture: x86
            sourcefile: string.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019
          - compiler: cl
            architecture: x86
            sourcefile: string_view.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019
          - compiler: cl
            architecture: x86
            sourcefile: uint32.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019
          - compiler: cl
            architecture: x86
            sourcefile: uint64.cpp
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /D "HAVE_ABSEIL" /EHsc /MD /Fe:benchmark.exe
            outputfile: benchmark.exe            
            os: windows-2019

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install Boost
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          git clone https://github.com/boostorg/boost.git boost-root
          cd boost-root
          git checkout boost-1.78.0
          git submodule update --init
          cmd /c bootstrap.bat
          .\b2.exe -d0 headers
      - name: Install Abseil
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          git clone -b lts_2021_11_02 https://github.com/abseil/abseil-cpp.git abseil-root
      - name: Install fastrange
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          git clone https://github.com/lemire/fastrange.git fastrange-root
      - name: Compile
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{matrix.architecture}}
          set INCLUDE=%INCLUDE%;%GITHUB_WORKSPACE%\boost-root
          set INCLUDE=%INCLUDE%;%GITHUB_WORKSPACE%\abseil-root
          set INCLUDE=%INCLUDE%;%GITHUB_WORKSPACE%\fastrange-root
          echo %INCLUDE%
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.compileroptions}}
      - name: Run benchmark
        shell: cmd
        run: |
          if [ -n "${{matrix.command}}" ]; then
              ${{matrix.command}}
          else
              ./${{matrix.outputfile}}
          fi

